// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("WebApi")>]
[<assembly: AssemblyProductAttribute("Oddjob")>]
[<assembly: AssemblyDescriptionAttribute("Engine for uploading files to cdn")>]
[<assembly: AssemblyVersionAttribute("1.25.24")>]
[<assembly: AssemblyFileVersionAttribute("1.25.24")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] Version = "1.25.24"
    let [<Literal>] InformationalVersion = "1.25.24"
